class DBF:
    rows: int
    cols: int

    @staticmethod
    def read(path: str) -> "DBF": ...
    def field_names(self) -> list[str]: ...
    def get_column(self, name: str) -> "Column": ...
    def to_csv(self, path: str) -> None: ...
    def to_parquet(self, path: str) -> None: ...

class Column:
    name: str

    def sum(self) -> float | None: ...
    def mean(self) -> float | None: ...
    def min(self) -> str | None: ...
    def max(self) -> str | None: ...
    def count(self) -> int: ...
    def unique(self) -> list[str]: ...
    def to_list(self) -> list[str | None]: ...
